steps:
# Pull the existing image
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/tomcat:latest || exit 0
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tomcat', '--cache-from', 'gcr.io/$PROJECT_ID/tomcat', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/$PROJECT_ID/tomcat"]
# This step deploys your image in kubernetes cluster specfied in below env
 - name: 'gcr.io/cloud-builders/kubectl'
   id: Deploy
   args:
    - 'apply'
    - '-f'
    - 'deploy.yaml',
    
    - 'apply'
    - '-f'
    - 'service.yaml
    
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gcpcluster'

