kind: Pod
apiVersion: v1
metadata:
  name: tomcat-vol-pod
spec:
  containers:
    - name: frontend
      image: gcr.io/resounding-rune-310809/tomcat
      volumeMounts:
      - mountPath: "/vol/test"
        name: tomcat-vol-pod
  volumes:
    - name: tomcat-vol-pod
      persistentVolumeClaim:
        claimName: tomcat-volume-disk
